codecov:
  branch: develop
  notify:
    require_ci_to_pass: yes
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    irc:
      default:
        server: freenode.net
        branches: develop

  status:
    project:
      default:
        target: auto
        threshold: 0.1%
        branches: null
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error


comment:
  layout: "header, diff, changes, uncovered"
  branches: null
  behavior: default
  flags: null
  paths: null

